/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for resume data structure
 */
export interface ResumeData {
  personal: {
    /**
     * Full name
     */
    name: string;
    /**
     * Professional title
     */
    title: string;
    /**
     * City, Country
     */
    location: string;
    /**
     * URL or path to photo
     */
    photo?: string;
    [k: string]: unknown;
  };
  /**
   * Professional summary
   */
  about: string;
  experience: {
    company: string;
    role: string;
    /**
     * e.g., 'Jan 2020 - Present'
     */
    period: string;
    location?: string;
    achievements?: string[];
    [k: string]: unknown;
  }[];
  skills: {
    /**
     * Skill category name
     */
    category: string;
    items: string[];
    [k: string]: unknown;
  }[];
  education: {
    institution: string;
    degree: string;
    period: string;
    location?: string;
    [k: string]: unknown;
  }[];
  contacts: {
    email: string;
    phone?: string;
    linkedin?: string;
    github?: string;
    website?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
